apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-test
  namespace: qna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe-test
  template:
    metadata:
      labels:
        app: fe-test
    spec:
      nodeSelector:
        role: core
      containers:
      - name: frontend
        image: lacet301/qna-internal-fe-test:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fe-test
  namespace: qna
spec:
  selector:
    app: fe-test
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30090