apiVersion: apps/v1
kind: Deployment
metadata:
  name: qna-frontend
  namespace: qna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qna-frontend
  template:
    metadata:
      labels:
        app: qna-frontend
    spec:
      nodeSelector:
        role: core
      containers:
      - name: frontend
        image: nmthanh31/finalproject-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: qna-frontend
  namespace: qna
spec:
  selector:
    app: qna-frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  type: NodePort